import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Map from '../../public/map.svg'

import Logo from '../../public/logo.svg'

import Button from '../../components/app-components/Button/Button'
import Link from 'next/link'

export default function DefaultLayout({children}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chrétiens Mâcon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Nova+Cut&display=swap" rel="stylesheet" /> 
      </Head>

      <div className="informative-header">
        <div className="informative-container">
          <div>
            <button>
              <a href="https://autun.catholique.fr/">Diocèse d'Autun</a>
            </button>
          </div>
          <div>Pas de paroisse</div>
        </div>
      </div>
      <header>
        <div className="header-container">
          <div className="logo-container">
            <Link href={'/'}>
              <Image src={Logo} alt="Chrétiens Mâcon"/>
            </Link>
          </div>
          <div className='nav-container'>
            <div>
              <Link className="nav-link" href={'/actualites'}>
                Actualités
              </Link>
            </div>
            <div>
              <Link className="nav-link" href={'/informations'}>
                Informations
              </Link>
            </div>
            <div>
              <Link className="nav-link" href={'/horaires'}>
                Horaires
              </Link>
            </div>
            <div>
              <Link className="nav-link" href={'/annuaire'}>
                Annuaire
              </Link>
            </div>
          </div>
        </div>
      </header>

      <main className="main-container">
        {children}
      </main>

      <footer className={styles.footer}>
          Développé par et pour le Mâconnais
      </footer>
    </div>
  )
}